user_authentication/basicapp/urls.py
from django.urls import path
from basicapp import views

#template url

app_name='basicapp'

urlpatterns=[
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login')
]

user_authentication/user_authentication/urls.py
from django.contrib import admin
from django.urls import path,include
from basicapp import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basicapp/',include('basicapp.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special')
]

user_authentication/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)

    #addditional 
    portfolio_site=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)


    def __str__(self):
        return self.user.username
    

user_authentication/basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicapp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields=('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('portfolio_site','profile_pic')
        

user_authentication/basicapp/views.py
from django.shortcuts import render
from basicapp.forms import UserForm,UserProfileInfoForm

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login,logout
# Create your views here.

def index(request):
    return render(request,'basicapp/index.html')

def register(request):
    registered=False
    if request.method =='POST':
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)

        if( user_form.is_valid() and profile_form.is_valid()):
            user=user_form.save()
            user.set_password(user.password)
            user.save()

            profile=profile_form.save(commit=False)
            profile.user=user

            if( 'profile_pic' in request.FILES ):
                profile.profile_pic=request.FILES['profile_pic']


            profile.save()

            registered=True
        else:
            print(user_form.errors,profile_form.errors)


    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()

    return render(request,'basicapp/registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})        
    

def user_login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(username=username,password=password)
        print('------function view.user_login---------')
        if user:
            print('------function view.user_login2---------')
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
                 
            else:
                return HttpResponse('Account NOT Active')
             
        else:
            print('Someone tried to login and failed')
            print('Username: {} and password {}'.format(username,password))
            return HttpResponse('invalid login details supplied')
        
    else:
        return render(request,'basicapp/login.html',{})
            

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse('You are Logged in ,NICE!')

user_authentication/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index'%}">DJANGO</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">ADMIN</a></li>
                <li><a class="navbar-link" href="{% url 'basicapp:register' %}">REGISTER</a></li>                 
                {% if user.is_authenticated %}
                    <li><a class="navbar-link" href="{% url 'logout' %}">LOGOUT</a></li>
                {% else %}
                    <li><a class="navbar-link" href="{% url 'basicapp:user_login' %}">LOGIN</a></li>
                
                {% endif %}
            </ul>
        </div>    
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
</body>
</html>

user_authentication/templates/basicapp/index.html
{% extends "basicapp/base.html" %}

{% block body_block %}

<div class="jumbotron">
    <h1>Django Level Five</h1>
</div>

{% endblock %}

user_authentication/templates/basicapp/login.html
{% extends 'basicapp/base.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1>PLease Login</h1>
    <form action="{% url 'basicapp:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password">

        <input type="submit" name="" value="Login">
    </form>
</div>

{% endblock %}

user_authentication/templates/basicapp/registration.html
{% extends 'basicapp/base.html' %}
{% load static %}

{% block body_block %}

<div class="jumbotron">
    {% if registered %}
        <h1>Thank you for registering</h1>
    {% else %}
        <h1>Register Here</h1>
        <h3>Fill out The Form:</h3>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="" value="Register">
        </form>
    {% endif %}
</div>

{% endblock %}